:)
js-tasks-ru/jsbasic-20230911_victorbushmin67 pull request #4
Opened 2023-09-27 20:28 UTC by the-christmas

2023-09-27 20:29 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-30 11:59 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return namesBalance.join('\n');
Давай тут заиспользуем методы массива:
```
users.filter(....).map(....).join('\n')
```

2023-09-30 18:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-30 18:51 UTC, the-christmas commented
:)

2023-09-30 18:55 UTC, the-christmas commented on 3-module/4-task/index.js
> +  return namesBalance.join('\n');
Vrode sdelal, vrode otoslal, no eto ne tochno :)

2023-09-30 18:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-10-02 14:46 UTC, SinimaWath requested changes

2023-10-02 14:46 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  document.body.append(list);
Не нужно пушить елемент в body, функция должна возвращать готовый DOM елемент, без document.body.append

2023-10-02 15:50 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-10-04 18:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-04 18:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-10-04 21:14 UTC, SinimaWath requested changes
у тебя полностью удалены папки:
- assets

Верни ее плиз

2023-10-05 18:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-10-05 18:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-10-07 15:01 UTC, SinimaWath approved these changes
все круто!

2023-10-07 15:03 UTC, merged